### Proc reinstall : 
#vi .ssh/known_hosts et delete old vps host
# 1) commenter .ssh/config en local
# ssh centos@vps-dff361cd.vps.ovh.net
# entrer le nouveau mot de passe reçu par mail
# vi .ssh/authorized_keys et mettre la clé publique ovh
#uncomment Host file from local
#now you can loggin via ssh without password
# copié clé github id_rsa dans .ssh
# lui donner les droits 600 chmod 600 id_rsa

# Install epel-repo puis python pip , puis ansible avec pip
# sudo yum -y install epel-release
# sudo yum repolist
#sudo -i
#rpm -Uvh http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
#rpm --import http://mirror.ghettoforge.org/distributions/gf/RPM-GPG-KEY-gf.el7
#yum -y remove vim-minimal vim-common vim-enhanced # removing  vim-minimal uninstalls `sudo`
#yum -y --enablerepo=gf-plus install vim-enhanced sudo
# exit sudo 
# sudo yum install -y python3
# sudo pip3 install --upgrade pip
# python3 -m pip install --user ansible
# verify with ansible-playbook --version
# scp -r ansible centos@vps-dff361cd.vps.ovh.net:/home/centos
# ansible-playbook -b ansible/install.yml
# copy signal data from laptop to /home/centos/data/signla-cli

- name: Copy file with owner and permissions
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: centos
    group: centos
    mode: '0644'
  with_items:
    - { src: '.bash_profile', dst: '/home/centos' }
    - { src: 'iptables.conf', dst: '/home/centos' }
    - { src: 'sshd_config', dst: '/etc/ssh/sshd_config' }
    - { src: 'paragliding-logrotate', dst: '/etc/logrotate.d' }

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install packages
  yum:
    name:
      - git
      - firefox
      - yum-utils
      - telnet
      - tcpdump
      - jq
      - fail2ban
    state: present

- name: Copy fail2ban config file
  ansible.builtin.copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'

- name: Restart sshd and fail2ban
  systemd:
    state: restarted
    name: "{{ item }}"
  with_items: 
    - sshd
    - fail2ban

- name: Add docker repo 
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    enabled: yes

- name: Ugly fix to docker repo
  command: sed -i 's/docker-ce.repo/7\/x86_64\/stable/' /etc/yum.repos.d/docker.repo

- name: Install docker packages
  yum:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - python-docker
    disable_gpg_check: yes
    state: present

- name: pip install docker
  command: pip3 install docker

- name: Make sure docker is started
  systemd:
    state: started
    name: docker

- name: Create shared docker volume directory
  file:
    path: /home/centos/data/signal-cli
    state: directory
    mode: '0755'
    recurse: yes
    
- name: Create a docker container
  docker_container:
    name: signal-api
    image: bbernhard/signal-cli-rest-api:0.112-dev
    published_ports: 8080:8080
    restart_policy: always
    volumes:
      - /home/centos/data/signal-cli:/home/.local/share/signal-cli 
    env:
        MODE: native

- name: Apply iptables config
  command: iptables-restore -n /home/centos/iptables.conf

- name: Create bin directory
  file:
    path: /home/centos/bin
    state: directory

- name: download geckodriver
  get_url: 
    url: https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
    dest: /tmp

- name: Untar gecko
  unarchive:
    src: /tmp/geckodriver-v0.32.0-linux64.tar.gz
    dest: /home/centos/bin
    mode: +x

- name: set timezone to Europe/Paris
  command: timedatectl set-timezone Europe/Paris

- name: Create a symbolic link to ansible-playbook for cron to run
  file:
    src: /home/centos/.local/bin/ansible-playbook
    dest: /usr/bin/ansible-playbook
    owner: centos
    group: centos
    state: link

- name: Send to website at 10, 13, 19,22
  cron:
    name: "launch_predictions website 2"
    user: "centos"
    weekday: "*"
    minute: "0"
    hour: "10,13,19,22"
    job: export PATH=$PATH:/home/centos/bin && ansible-playbook /home/centos/ansible/run.yml --e "pythonArgs='--spot-file=spots.json --html-file=all.markdown --send-to-website'" &>> /home/centos/log.log
    state: present

- name: Send to Signal and website twice a day at 7 and 17 h
  cron:
    name: "launch_predictions website and signal"
    user: "centos"
    weekday: "*"
    minute: "0"
    hour: "7,17"
    job: export PATH=$PATH:/home/centos/bin && ansible-playbook /home/centos/ansible/run.yml --extra-vars "pythonArgs=--send-to-signal" &>> /home/centos/log.log
    state: present