# Remove vim which remove sudo, then install latest version
#sudo -i
#rpm -Uvh http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm
#rpm --import http://mirror.ghettoforge.org/distributions/gf/RPM-GPG-KEY-gf.el7
#
## WARNING: removing  vim-minimal uninstalls `sudo` if you skip the second step
##          make sure to at least run `yum install sudo`
#yum -y remove vim-minimal vim-common vim-enhanced
#yum -y --enablerepo=gf-plus install vim-enhanced sudo

- name: Install packages
  yum:
    name:
      - git
      - firefox
    state: present

- name: Create bin directory
  file:
    path: /home/centos/bin
    state: directory

- name: download geckodriver
  get_url: 
    url: https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
    dest: /tmp

- name: Untar gecko
  unarchive:
    src: /tmp/geckodriver-v0.32.0-linux64.tar.gz
    dest: /home/centos/bin
    mode: +x

- name: add bin to path
  command: echo "export PATH=$PATH:/home/centos/bin" >> /home/centos/.bash_profile

- name: Run CRON job to launch prediction playbook at every 30th minute of every hour.
  cron:
    name: "launch_predictions"
    user: "centos"
    weekday: "*"
    minute: "30"
    hour: "*"
    job: "ap ansible/run.yml"
    state: present