- name: remove paragliding
  file:
    path: /home/centos/paragliding-forecast
    state: absent

- name: remove parapente
  file:
    path: /home/centos/parapente-dans-le-nord
    state: absent

- name: Clone paragliding-forecast
  git:
    repo: "git@github.com:mbriot/paragliding-forecast.git"
    dest: /home/centos/paragliding-forecast
    accept_hostkey: yes
    key_file: /home/centos/.ssh/id_rsa

- name: Clone parapente-dans-le-nord
  git:
    repo: "git@github.com:parapente-dans-le-nord/parapente-dans-le-nord.github.io.git"
    dest: /home/centos/parapente-dans-le-nord
    accept_hostkey: yes
    key_file: /home/centos/.ssh/id_rsa

- name: Make a venv
  shell:
    cmd: python3 -m venv .venv
    chdir: /home/centos/paragliding-forecast

- name: Activate venv
  shell:
    cmd: source .venv/bin/activate
    chdir: /home/centos/paragliding-forecast
    
- name: Install libs
  shell:
    cmd: python3 -m pip install -r requirements.txt
    chdir: /home/centos/paragliding-forecast

- name: Run python
  shell: 
    cmd: 'python3 src/main.py --config-file=/home/centos/config.json --spot-file=spots.json 
      -v --send-to-website {{ pythonArgs }} &>> /home/centos/log.log' 
    chdir: /home/centos/paragliding-forecast
  ignore_errors: true
  register: python_result

- name: Check that index.markdown exists
  stat:
    path: /home/centos/paragliding-forecast/index.markdown
  register: stat_result

- name: Move index.markdown in parapente-dans-le-nord
  shell:
    cmd: "mv {{ item }} /home/centos/parapente-dans-le-nord"
    chdir: /home/centos/paragliding-forecast
  with_items:
    - index.markdown
    - all.markdown
  when: stat_result.stat.exists

- name: commit
  shell:
    cmd: "{{ item }}"
    chdir: /home/centos/parapente-dans-le-nord
  with_items:
    - git add -A
    - git commit -am "update index.markdown"
    - git push
  when: stat_result.stat.exists

- name: remove paragliding
  file:
    path: /home/centos/paragliding-forecast
    state: absent

- name: remove parapente
  file:
    path: /home/centos/parapente-dans-le-nord
    state: absent

- name: Get selenium processes
  shell: "ps -ef  | grep -w marionette | grep -v grep | awk '{print $2}'"
  register: selenium_processes

- name: Kill selenium running processes
  shell: "kill {{ item }}"
  with_items: "{{ selenium_processes.stdout_lines }}"

- fail:
    msg: Python script failed !
  when: python_result.stderr | length > 0